### ISSUE TITLE
运行训练函数sh train报错问题

### ISSUE THREAD

**Issue by fjt12138** [S007-Chen/ADPN-MM#1]
感谢作者的工作，我在运行train脚本的时候，代码输出如下：

/anaconda3/envs/adpn/lib/python3.7/site-packages/nncore/__init__.py:12: UserWarning: Please install opencv-python to enable 'nncore.image'
  warnings.warn("Please install opencv-python to enable 'nncore.image'")
Segmentation fault

并没有开始训练。依照md中的流程，我很确定创建的环境符合yam的要求，能否请作者帮忙看一下

**Comment by hlchen23** [comment]
您的来件已收到，谢谢！（自动回复）Chen

**Comment by fjt12138** [comment]
我在环境下删除opencv-python包的目录，重新安装后解决了这个问题，有没有考虑是yaml文件关于opencv-python的依赖问题呢

**Comment by hlchen23** [comment]
你好！感谢你对这个工作的兴趣！yaml中的依赖配置是作者实验时的配置，本地复现时可能出现一些版本之间的冲突，自行调整一下版本即可。
