### ISSUE TITLE
是否有计划开源预训练模型

### ISSUE THREAD

**Issue by TheHonestBob** [S007-Chen/ADPN-MM#2]
如题，请问未来是否有计划开源预训练模型呢

**Comment by hlchen23** [comment]
您的来件已收到，谢谢！（自动回复）Chen

**Comment by hlchen23** [comment]
这篇工作构建的模型是一个面向grounding任务的模型，严格来说不算一个预训练模型。抽取vision和audio特征使用的预训练模型（C3D/I3D/PANN/VGGish，在论文中各有引用）是现有的已经开源的模型。
